name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run lint-staged
        run: npx lint-staged

      - name: Build Docker image
        run: |
          docker build -t docker.pkg.github.com/nicoleokamoto/react-ui-component-library/okamoto_nicole_assignment13 .
          docker login docker.pkg.github.com -u nicoleokamoto@icloud.com -p ${{ secrets.DOCKER_HUB_ACCESS }}
          docker tag docker.pkg.github.com/nicoleokamoto/react-ui-component-library/okamoto_nicole_assignment13:latest docker.pkg.github.com/nicoleokamoto/react-ui-component-library/okamoto_nicole_assignment13:latest
          docker push docker.pkg.github.com/nicoleokamoto/react-ui-component-library/okamoto_nicole_assignment13:latest

      - name: Push Docker image to Docker Hub (if needed)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            lastname_firstname_coding_assignment13:latest
