name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run lint-staged
        run: npx lint-staged

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: |
          docker login -u nicoleokamoto -p ${{ secrets.DOCKER_HUB_ACCESS }}

      - name: Build Docker image
        run: |
          docker build -t nicoleokamoto/react-ui-component-library:okamoto_nicole_assignment13 .

      - name: Push Docker image
        run: |
          docker push nicoleokamoto/react-ui-component-library:okamoto_nicole_assignment13
